apiVersion: v1
kind: ContinuousQuery
name: freezer
spec:
  mode: query
  sources:    
    subscriptions:
      - id: daniel-test
  query: > 
    MATCH 
      (f:Freezer)
    WHERE drasi.trueFor(f.temp > 32, duration( { seconds: 10 } ))
    RETURN
      f.id AS id,
      f.temp AS temp