# Copyright 2024 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ContinuousQuery
name: sensors-not-reporting
spec:
  mode: query
  sources:    
    subscriptions:
      - id: daniel-test
    joins:
      - id: HAS_SENSOR
        keys:
          - label: Equipment
            property: id
          - label: Sensor
            property: equipment_id
      - id: HAS_VALUE
        keys:
          - label: Sensor
            property: id
          - label: SensorValue
            property: sensor_id
  query: > 
    MATCH
        (e:Equipment)-[:HAS_SENSOR]->(s:Sensor)-[:HAS_VALUE]->(v:SensorValue)
    WITH
        e.name AS equipment,
        s.type AS sensor,
        max(drasi.changeDateTime(v)) AS last_ts
    WHERE 
        last_ts <= (datetime.realtime() - duration( { seconds: 10 } ))        
    OR
        drasi.trueLater(last_ts <= (datetime.realtime() - duration( { seconds: 10 } )), last_ts + duration( { seconds: 10 } ))
    RETURN
        equipment AS equipment,
        sensor AS sensor,
        last_ts AS last_ts