apiVersion: v1
kind: Source
name: demo-devops
spec:
  kind: PostgreSQL
  properties:
    host: reactive-graph.postgres.database.azure.com
    user: postgres@reactive-graph
    port: 5432
    ssl: true
    password:
      kind: Secret
      name: pg-creds
      key: password
    database: demo-devops
    tables:
      - public.RiskyImage