# Copyright 2024 The Drasi Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ContinuousQuery
apiVersion: v1
name: demo-query1
spec:
  mode: query
  sources:    
    subscriptions:
      - id: k8s
  query: > 
    MATCH 
      (p:Pod)-[:HOSTS]->(c:Container) 
    WHERE c.name = 'redis'
    RETURN 
      p.name as Pod,
      p.phase as PodPhase,
      p.message as PodMessage,
      c.name as Container,
      c.image as Image,
      c.started as Started,
      c.ready as Ready,
      c.restartCount as RestartCount,
      c.state as State,
      c.reason as Reason,
      c.message as Message
---
kind: ContinuousQuery
apiVersion: v1
name: risky-containers
spec:
  mode: query
  sources:    
    subscriptions:
      - id: k8s
        nodes:
          - sourceLabel: Container
          - sourceLabel: Pod
        relations:
          - sourceLabel: HOSTS
      - id: demo-devops
        nodes:
          - sourceLabel: RiskyImage
    joins:
      - id: INCLUDES
        keys:
          - label: RiskyImage
            property: Image
          - label: Container
            property: image
  query: > 
    MATCH 
      (r:RiskyImage)-[:INCLUDES]->(c:Container)<-[:HOSTS]-(p:Pod)
    RETURN 
      p.name as Pod,
      c.name as Container,
      c.image as Image,
      c.started as Started,
      c.ready as Ready,
      c.state as State,
      c.reason as Reason,
      c.message as Message,
      r.Reason as Risk
---
kind: ContinuousQuery
apiVersion: v1
name: my-apps
spec:
  mode: query
  sources:    
    subscriptions:
      - id: k8s
  query: > 
    MATCH 
      (p:Pod)-[:HOSTS]->(c:Container) 
    WHERE c.name = 'app'
    RETURN 
      p.name as Pod,
      p.phase as PodPhase,
      p.message as PodMessage,
      c.name as Container,
      c.image as Image,
      c.started as Started,
      c.ready as Ready,
      c.restartCount as RestartCount,
      c.state as State,
      c.reason as Reason,
      c.message as Message
