kind: ContinuousQuery
apiVersion: v1
name: building-comfort-level-calc
spec:
  mode: query
  sources:
    subscriptions:
      - id: facilities
  query: > 
    MATCH 
      (f:Floor)-[:PART_OF]->(b:Building) 
    RETURN 
      elementId(b) AS BuildingId, avg(f.comfortLevel) AS ComfortLevel
---
kind: ContinuousQuery
apiVersion: v1
name: floor-comfort-level-calc
spec:
  mode: query
  sources:
    subscriptions:
      - id: facilities
  query: > 
    MATCH 
      (r:Room)-[:PART_OF]->(f:Floor) 
    RETURN 
      elementId(f) AS FloorId, avg(r.comfortLevel) AS ComfortLevel
---
kind: ContinuousQuery
apiVersion: v1
name: room-comfort-level-calc
spec:
  mode: query
  sources:
    subscriptions:
      - id: facilities
  query: > 
    MATCH 
      (r:Room) 
    RETURN 
      elementId(r) AS RoomId,
      floor( 50 + (r.temp - 72) + (r.humidity - 42) + CASE WHEN r.co2 > 500 THEN (r.co2 - 500) / 25 ELSE 0 END ) AS ComfortLevel