kind: ContinuousQuery
apiVersion: v1
name: building-alert
spec:
  mode: query
  sources:
    subscriptions:
      - id: facilities
  query: >
    MATCH 
      (b:Building) 
    WHERE b.comfortLevel < 40 OR b.comfortLevel > 50 
    RETURN 
      elementId(b) AS BuildingId, b.name AS BuildingName, b.comfortLevel AS ComfortLevel
---
kind: ContinuousQuery
apiVersion: v1
name: floor-alert
spec:
  mode: query
  sources:
    subscriptions:
      - id: facilities
  query: >
    MATCH 
      (f:Floor) 
    WHERE f.comfortLevel < 40 OR f.comfortLevel > 50 
    RETURN 
      elementId(f) AS FloorId, elementId(f) AS FloorName, f.comfortLevel AS ComfortLevel
---
kind: ContinuousQuery
apiVersion: v1
name: room-alert
spec:
  mode: query
  sources:
    subscriptions:
      - id: facilities
  query: >
    MATCH 
      (r:Room) 
    WHERE r.comfortLevel < 40 OR r.comfortLevel > 50 
    RETURN 
      elementId(r) AS RoomId, r.name AS RoomName, r.comfortLevel AS ComfortLevel