apiVersion: v1
kind: Reaction
name: room-comfort-level-calc-gremlin
spec:
  kind: Gremlin
  queries:
    room-comfort-level-calc: 
  properties:
    AddedResultCommand: g.V('@RoomId').hasLabel('Room').property('comfortLevel', @ComfortLevel )
    UpdatedResultCommand: g.V('@after.RoomId').hasLabel('Room').property('comfortLevel', @after.ComfortLevel )
    DatabaseHost:
      kind: Secret
      name: comfy-gremlin
      key: DatabaseHost
    DatabasePrimaryKey:
      kind: Secret
      name: comfy-gremlin
      key: DatabasePrimaryKey
    DatabaseName: Contoso
    DatabaseContainerName: Facilities
    DatabasePort: "443"
---
apiVersion: v1
kind: Reaction
name: floor-comfort-level-calc-gremlin
spec:
  kind: Gremlin
  queries:
    room-comfort-level-calc: 
  properties:
    AddedResultCommand: g.V('@FloorId').hasLabel('Floor').property('comfortLevel', @ComfortLevel)
    UpdatedResultCommand: g.V('@after.FloorId').hasLabel('Floor').property('comfortLevel', @after.ComfortLevel)
    DatabaseHost:
      kind: Secret
      name: comfy-gremlin
      key: DatabaseHost
    DatabasePrimaryKey:
      kind: Secret
      name: comfy-gremlin
      key: DatabasePrimaryKey
    DatabaseName: Contoso
    DatabaseContainerName: Facilities
    DatabasePort: "443"
---
apiVersion: v1
kind: Reaction
name: building-comfort-level-calc-gremlin
spec:
  kind: Gremlin
  queries:
    room-comfort-level-calc: 
  properties:
    AddedResultCommand: g.V('@BuildingId').hasLabel('Building').property('comfortLevel', @ComfortLevel)
    UpdatedResultCommand: g.V('@after.BuildingId').hasLabel('Building').property('comfortLevel', @after.ComfortLevel)
    DatabaseHost:
      kind: Secret
      name: comfy-gremlin
      key: DatabaseHost
    DatabasePrimaryKey:
      kind: Secret
      name: comfy-gremlin
      key: DatabasePrimaryKey
    DatabaseName: Contoso
    DatabaseContainerName: Facilities
    DatabasePort: "443"