kind: Source
apiVersion: v1
name: facilities
spec:
  kind: CosmosGremlin
  services:
    reactivator:
      properties:
        partitionKey: name
  properties:
    accountEndpoint:
      kind: Secret
      name: comfy-creds
      key: accountEndpoint
    database: Contoso
    container: Facilities