apiVersion: v1
kind: SourceProvider
name: EventHub
spec: 
  services:
    proxy:
      image: source-eventhub-proxy
      dapr:
        app-port: "80"
    reactivator: 
      image: source-eventhub-reactivator
  config_schema:
    type: object
    properties:
      connectionString:
        type: string
      consumerGroup:
        type: string
        default: "$Default"
      eventHubs:
        type: array
      bootstrapWindow:
        type: integer
        default: 0
    required:
      - connectionString
      - eventHubs
