apiVersion: v1
kind: ContinuousQuery
name: risky-containers
spec:
  mode: query
  sources:    
    subscriptions:
      - id: k8s
        nodes:
          - sourceLabel: Pod
        pipeline:
          - extract-containers
      - id: devops
        nodes:
          - sourceLabel: RiskyImage
    joins:
      - id: HAS_IMAGE
        keys:
          - label: RiskyImage
            property: Image
          - label: Container
            property: image
    middleware:
      - kind: unwind
        name: extract-containers
        Pod:
          - selector: $.status.containerStatuses[*]
            label: Container
            key: $.containerID
            relation: OWNS

  query: > 
    MATCH 
      (p:Pod)-[:OWNS]->(c:Container)-[:HAS_IMAGE]->(i:RiskyImage)    
    RETURN
      p.name as pod,
      c.image as image,
      c.name as name,
      c.ready as ready,
      c.started as started,
      c.restartCount as restartCount,
      i.Reason as reason