kind: Source
apiVersion: v1
name: games
spec:
  kind: CosmosGremlin
  services:
    reactivator: 
      properties:
        partitionKey: partition
  properties:
    accountEndpoint:
      kind: Secret
      name: trivia-creds
      key: accountEndpoint
    database: Contoso
    container: Trivia

