name: Upload tutorial zip


on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout

jobs:
  archive_and_upload:
    runs-on: ubuntu-latest
    environment: learning
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip folder
        run: |
          zip -r quickstart-dev-container.zip ./tutorial

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: Upload to Azure Storage Blob
        run: |
           az storage blob upload --file quickstart-dev-container.zip --container-name tutorials --overwrite --name quickstart-dev-container.zip --account-name drasi

